---
driver:
  name: vagrant
  synced_folders:
      - ['test', '/tmp/tests', 'create: true', owner: "root", group: "root"]
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  policyfile: policies/chef-automate2.rb
  always_update_cookbooks: true
  # product_name: chef
  # product_version: 13.8.5

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
  - name: aib
    provisioner:
      named_run_list: aib
    verifier:
      inspec_tests:
        - test/integration/default
  - name: full
    provisioner:
      named_run_list: full
    verifier:
      inspec_tests:
        - test/integration/default
